baseURL = "https://msdblog.de"
languageCode = "de"
title = "MSD Blog"
theme = "kiss"
Paginate = 5 # Number of posts per page
enableRobotsTXT = true
copyright = "&copy; <a href=\"https://github.com/deisi\">Malte Deiseroth</a> 2020"

[params.rss] # Adding this tag enables RSS feed
includeContent = true # Includes whole content in rss
authorName = "Malte Deiseroth" # Author full name
authorEmail = "mdeiseroth88@gmail.com" # Author email

[params.info]
homeTitle = "MSDBlog" # Title for home page
poweredby = true # Adds powered by hugo and kiss below Copyright
related = true # Includes related articles at the bottom of the article
codeCopy = true # Add copy button above code blocks

[params.social]
github = "deisi"
email = "mdeiseroth88@gmail.com"
rss = "index.xml" # Add this to show RSS button in social.

[params.social.config]
platforms = ["github","email", "rss"]

[params.sections_right]
"https://msdblog.de/about" = "About/Impressum/Datenschutz"

[taxonomies]
tag ="tags"